# Generated by Django 5.2.4 on 2025-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_benefits_product_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текстовое поле'), ('email', 'Email'), ('phone', 'Телефон'), ('number', 'Число'), ('date', 'Дата'), ('select', 'Выпадающий список'), ('textarea', 'Многострочный текст')], max_length=20, verbose_name='Тип поля'),
        ),
    ]
