# Generated by Django 5.2.4 on 2025-08-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['page_name', 'section_name', 'content_key']},
        ),
    ]
